name: mongodb-release-deployment
releases:
  - name: &release_name mongodb-release
    version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: mongo-config
  instances: 3
  jobs:
  - name: mongo-config
    release: *release_name
    consumes:
      peer_servers:
        from: mongo-config
    provides:
      servers:
        as: mongo-config
  properties:
    mongodb:
      keyfile: |
        Si3ro+EPlvm+Mh51yRPW/y8Uwb+CYtRpAraffnkghK3vHbSl3D6GyZaLSrrqJf3U
        no9XyH0afUAgsUpx5nztOj+Xb3HPxvbzDkbwxCYI69NL/ckyH9J4raSEriTaxJ0B
        mA7LJicQdOXOMYGk29QsEZxfFLtWw43gVidp0FfFm8AC0LjZPvVEUHq0o4oFR+v8
        HM/tFwrfM7doCk3J8+XWVVzJ0ZIiMd+q7Ldpqr6SwIiuO0kXqbvBG3gqVjZUVc7l
        kPIxVqKdH2BcbFzdQU1P9wuQRk1gw576tx+OnS6Sbd1KcNrjN06N5zRns+7xfckT
        pIgehSkjh2N4uHF9KGn/7V953Ttn//UNPpWTvXbfn3r6Hu4AnYE+m5T+b9krIbIb
        pGP60hUXhSXkYVdMHR6AM/9HBIYxAcDBLGvOB74oNl+FH485Yk8Xja8SA8JB8iiS
        l3KYtmiOtY21JH0Ri0Tlf7TMxqoNCcpyZpPA8/ZsofBdZHrLfCpvREX6x3jKzxcF
        OLaGSncJYT024V5hEGFv6zGzehWvKi2CGn1DjFpmtRQS7G+nfoGEe1bpzyxqZmrn
        oBbBLZCEevkRC2m5XvdUcb5BkNyJhWAHVNtrXtDgdy0bYhGOBnaf3MVCjvAh1ybH
        MucmQF5JaoSd3eMaOJFueZw9M1bIqtvq6xxCN2Rw9jyPYwueg5gvMY7AU/QmbPlZ
        gc2vXZ60Xb42AZJ84JeptTp+OchW99ONAmsaZPMh7xX7WbyMdr/Nn6Ts9AiloPib
        FhmWpqjLagztuYKUrRy7t3hc06K6jxcidMJ2kj1mC7cCun5wxEK1/kKGtD1xr1/B
        7ZcAiHMa9NjBjz/0DXX0tCWOxj3A/IULIBTbu3SXdbeL7u9YlKHCC16d8i1udWbz
        lcTXL7ADYw/xYiCuyElARxMdB1htiiofYhzkxRMsW0ri1u1WwTwGFrSCeo70Cops
        5oqcP9b4yujo/3eMKZ64E4kFTXL3jSxCkRW8BgsRq7zReazk
  vm_type: medium
  persistent_disk_type: ten
  stemcell: trusty
  networks:
  - name: &network_name mongodb-release-network

- name: mongos
  instances: 3
  jobs:
  - name: mongos
    release: *release_name
    consumes:
      peer_servers:
        from: mongos
      config_servers:
        from: mongo-config
    provides:
      servers:
        as: mongos

  properties:
    mongodb:
      keyfile: |
        Si3ro+EPlvm+Mh51yRPW/y8Uwb+CYtRpAraffnkghK3vHbSl3D6GyZaLSrrqJf3U
        no9XyH0afUAgsUpx5nztOj+Xb3HPxvbzDkbwxCYI69NL/ckyH9J4raSEriTaxJ0B
        mA7LJicQdOXOMYGk29QsEZxfFLtWw43gVidp0FfFm8AC0LjZPvVEUHq0o4oFR+v8
        HM/tFwrfM7doCk3J8+XWVVzJ0ZIiMd+q7Ldpqr6SwIiuO0kXqbvBG3gqVjZUVc7l
        kPIxVqKdH2BcbFzdQU1P9wuQRk1gw576tx+OnS6Sbd1KcNrjN06N5zRns+7xfckT
        pIgehSkjh2N4uHF9KGn/7V953Ttn//UNPpWTvXbfn3r6Hu4AnYE+m5T+b9krIbIb
        pGP60hUXhSXkYVdMHR6AM/9HBIYxAcDBLGvOB74oNl+FH485Yk8Xja8SA8JB8iiS
        l3KYtmiOtY21JH0Ri0Tlf7TMxqoNCcpyZpPA8/ZsofBdZHrLfCpvREX6x3jKzxcF
        OLaGSncJYT024V5hEGFv6zGzehWvKi2CGn1DjFpmtRQS7G+nfoGEe1bpzyxqZmrn
        oBbBLZCEevkRC2m5XvdUcb5BkNyJhWAHVNtrXtDgdy0bYhGOBnaf3MVCjvAh1ybH
        MucmQF5JaoSd3eMaOJFueZw9M1bIqtvq6xxCN2Rw9jyPYwueg5gvMY7AU/QmbPlZ
        gc2vXZ60Xb42AZJ84JeptTp+OchW99ONAmsaZPMh7xX7WbyMdr/Nn6Ts9AiloPib
        FhmWpqjLagztuYKUrRy7t3hc06K6jxcidMJ2kj1mC7cCun5wxEK1/kKGtD1xr1/B
        7ZcAiHMa9NjBjz/0DXX0tCWOxj3A/IULIBTbu3SXdbeL7u9YlKHCC16d8i1udWbz
        lcTXL7ADYw/xYiCuyElARxMdB1htiiofYhzkxRMsW0ri1u1WwTwGFrSCeo70Cops
        5oqcP9b4yujo/3eMKZ64E4kFTXL3jSxCkRW8BgsRq7zReazk
  vm_type: medium
  persistent_disk_type: ten
  stemcell: trusty
  networks:
  - name: &network_name mongodb-release-network

- name: shard0
  instances: 3
  jobs:
  - name: mongo-shard
    release: *release_name
    provides:
      peer_servers: {as: shard0}
    consumes:
      peer_servers: {from: shard0}
      mongos_servers: {from: mongos}
  properties:
    mongodb:
      keyfile: |
        Si3ro+EPlvm+Mh51yRPW/y8Uwb+CYtRpAraffnkghK3vHbSl3D6GyZaLSrrqJf3U
        no9XyH0afUAgsUpx5nztOj+Xb3HPxvbzDkbwxCYI69NL/ckyH9J4raSEriTaxJ0B
        mA7LJicQdOXOMYGk29QsEZxfFLtWw43gVidp0FfFm8AC0LjZPvVEUHq0o4oFR+v8
        HM/tFwrfM7doCk3J8+XWVVzJ0ZIiMd+q7Ldpqr6SwIiuO0kXqbvBG3gqVjZUVc7l
        kPIxVqKdH2BcbFzdQU1P9wuQRk1gw576tx+OnS6Sbd1KcNrjN06N5zRns+7xfckT
        pIgehSkjh2N4uHF9KGn/7V953Ttn//UNPpWTvXbfn3r6Hu4AnYE+m5T+b9krIbIb
        pGP60hUXhSXkYVdMHR6AM/9HBIYxAcDBLGvOB74oNl+FH485Yk8Xja8SA8JB8iiS
        l3KYtmiOtY21JH0Ri0Tlf7TMxqoNCcpyZpPA8/ZsofBdZHrLfCpvREX6x3jKzxcF
        OLaGSncJYT024V5hEGFv6zGzehWvKi2CGn1DjFpmtRQS7G+nfoGEe1bpzyxqZmrn
        oBbBLZCEevkRC2m5XvdUcb5BkNyJhWAHVNtrXtDgdy0bYhGOBnaf3MVCjvAh1ybH
        MucmQF5JaoSd3eMaOJFueZw9M1bIqtvq6xxCN2Rw9jyPYwueg5gvMY7AU/QmbPlZ
        gc2vXZ60Xb42AZJ84JeptTp+OchW99ONAmsaZPMh7xX7WbyMdr/Nn6Ts9AiloPib
        FhmWpqjLagztuYKUrRy7t3hc06K6jxcidMJ2kj1mC7cCun5wxEK1/kKGtD1xr1/B
        7ZcAiHMa9NjBjz/0DXX0tCWOxj3A/IULIBTbu3SXdbeL7u9YlKHCC16d8i1udWbz
        lcTXL7ADYw/xYiCuyElARxMdB1htiiofYhzkxRMsW0ri1u1WwTwGFrSCeo70Cops
        5oqcP9b4yujo/3eMKZ64E4kFTXL3jSxCkRW8BgsRq7zReazk
      replSetName: shard0
  vm_type: medium
  persistent_disk_type: ten
  stemcell: trusty
  networks:
  - name: &network_name mongodb-release-network


- name: shard1
  instances: 3
  jobs:
  - name: mongo-shard
    release: *release_name
    provides:
      peer_servers: {as: shard1}
    consumes:
      peer_servers: {from: shard1}
      mongos_servers: {from: mongos}
  properties:
    mongodb:
      keyfile: |
        Si3ro+EPlvm+Mh51yRPW/y8Uwb+CYtRpAraffnkghK3vHbSl3D6GyZaLSrrqJf3U
        no9XyH0afUAgsUpx5nztOj+Xb3HPxvbzDkbwxCYI69NL/ckyH9J4raSEriTaxJ0B
        mA7LJicQdOXOMYGk29QsEZxfFLtWw43gVidp0FfFm8AC0LjZPvVEUHq0o4oFR+v8
        HM/tFwrfM7doCk3J8+XWVVzJ0ZIiMd+q7Ldpqr6SwIiuO0kXqbvBG3gqVjZUVc7l
        kPIxVqKdH2BcbFzdQU1P9wuQRk1gw576tx+OnS6Sbd1KcNrjN06N5zRns+7xfckT
        pIgehSkjh2N4uHF9KGn/7V953Ttn//UNPpWTvXbfn3r6Hu4AnYE+m5T+b9krIbIb
        pGP60hUXhSXkYVdMHR6AM/9HBIYxAcDBLGvOB74oNl+FH485Yk8Xja8SA8JB8iiS
        l3KYtmiOtY21JH0Ri0Tlf7TMxqoNCcpyZpPA8/ZsofBdZHrLfCpvREX6x3jKzxcF
        OLaGSncJYT024V5hEGFv6zGzehWvKi2CGn1DjFpmtRQS7G+nfoGEe1bpzyxqZmrn
        oBbBLZCEevkRC2m5XvdUcb5BkNyJhWAHVNtrXtDgdy0bYhGOBnaf3MVCjvAh1ybH
        MucmQF5JaoSd3eMaOJFueZw9M1bIqtvq6xxCN2Rw9jyPYwueg5gvMY7AU/QmbPlZ
        gc2vXZ60Xb42AZJ84JeptTp+OchW99ONAmsaZPMh7xX7WbyMdr/Nn6Ts9AiloPib
        FhmWpqjLagztuYKUrRy7t3hc06K6jxcidMJ2kj1mC7cCun5wxEK1/kKGtD1xr1/B
        7ZcAiHMa9NjBjz/0DXX0tCWOxj3A/IULIBTbu3SXdbeL7u9YlKHCC16d8i1udWbz
        lcTXL7ADYw/xYiCuyElARxMdB1htiiofYhzkxRMsW0ri1u1WwTwGFrSCeo70Cops
        5oqcP9b4yujo/3eMKZ64E4kFTXL3jSxCkRW8BgsRq7zReazk
      replSetName: shard1
  vm_type: medium
  persistent_disk_type: ten
  stemcell: trusty
  networks:
  - name: &network_name mongodb-release-network

- name: shard2
  instances: 3
  jobs:
  - name: mongo-shard
    release: *release_name
    provides:
      peer_servers: {as: shard2}
    consumes:
      peer_servers: {from: shard2}
      mongos_servers: {from: mongos}
  properties:
    mongodb:
      keyfile: |
        Si3ro+EPlvm+Mh51yRPW/y8Uwb+CYtRpAraffnkghK3vHbSl3D6GyZaLSrrqJf3U
        no9XyH0afUAgsUpx5nztOj+Xb3HPxvbzDkbwxCYI69NL/ckyH9J4raSEriTaxJ0B
        mA7LJicQdOXOMYGk29QsEZxfFLtWw43gVidp0FfFm8AC0LjZPvVEUHq0o4oFR+v8
        HM/tFwrfM7doCk3J8+XWVVzJ0ZIiMd+q7Ldpqr6SwIiuO0kXqbvBG3gqVjZUVc7l
        kPIxVqKdH2BcbFzdQU1P9wuQRk1gw576tx+OnS6Sbd1KcNrjN06N5zRns+7xfckT
        pIgehSkjh2N4uHF9KGn/7V953Ttn//UNPpWTvXbfn3r6Hu4AnYE+m5T+b9krIbIb
        pGP60hUXhSXkYVdMHR6AM/9HBIYxAcDBLGvOB74oNl+FH485Yk8Xja8SA8JB8iiS
        l3KYtmiOtY21JH0Ri0Tlf7TMxqoNCcpyZpPA8/ZsofBdZHrLfCpvREX6x3jKzxcF
        OLaGSncJYT024V5hEGFv6zGzehWvKi2CGn1DjFpmtRQS7G+nfoGEe1bpzyxqZmrn
        oBbBLZCEevkRC2m5XvdUcb5BkNyJhWAHVNtrXtDgdy0bYhGOBnaf3MVCjvAh1ybH
        MucmQF5JaoSd3eMaOJFueZw9M1bIqtvq6xxCN2Rw9jyPYwueg5gvMY7AU/QmbPlZ
        gc2vXZ60Xb42AZJ84JeptTp+OchW99ONAmsaZPMh7xX7WbyMdr/Nn6Ts9AiloPib
        FhmWpqjLagztuYKUrRy7t3hc06K6jxcidMJ2kj1mC7cCun5wxEK1/kKGtD1xr1/B
        7ZcAiHMa9NjBjz/0DXX0tCWOxj3A/IULIBTbu3SXdbeL7u9YlKHCC16d8i1udWbz
        lcTXL7ADYw/xYiCuyElARxMdB1htiiofYhzkxRMsW0ri1u1WwTwGFrSCeo70Cops
        5oqcP9b4yujo/3eMKZ64E4kFTXL3jSxCkRW8BgsRq7zReazk
      replSetName: shard2
  vm_type: medium
  persistent_disk_type: ten
  stemcell: trusty
  networks:
  - name: &network_name mongodb-release-network

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
